### ISSUE TITLE
Design a figma prototype

### ISSUE THREAD

**Issue by Gaurav-45** [Premkolte/AnimateHub#1]
Create a Figma prototype and finalize
1. Create a Light theme figma design
2. Creat a dark theme Figma design

Acceptance criteria:
Finalize the theme with the project admin and start designing the architecture.

**Comment by Premkolte** [comment]
https://www.figma.com/design/glBUKjxyRA8iLPMkry1vQK/Animation-Hub?node-id=1-2&t=GZQuUsjYUCveD3yi-1

This is the Figma design for the Animation-Hub
(you can ask for edit access to @Premkolte ,and start contributing.)

**Comment by kom-senapati** [comment]
Give me access - komnoob123@gmail.com

**Comment by Premkolte** [comment]
Done

**Comment by Premkolte** [comment]
> Give me access - [komnoob123@gmail.com](mailto:komnoob123@gmail.com)

Done

**Comment by kom-senapati** [comment]
Yeah I can do this in tailwind

**Comment by Premkolte** [comment]
yes , you can do it.

**Comment by Premkolte** [comment]
we have finalised the UI.
