### ISSUE TITLE
added login and signup page

### ISSUE THREAD

**Issue by Krishna100604** [Premkolte/AnimateHub#110]
![Screenshot (174)](https://github.com/Premkolte/AnimateHub/assets/110299021/ff52db2d-10ce-4724-905d-d951ebb10862)
![Screenshot (173)](https://github.com/Premkolte/AnimateHub/assets/110299021/b8b0c080-42bb-4aee-82d7-600c69669fb2)
![Screenshot (175)](https://github.com/Premkolte/AnimateHub/assets/110299021/f54296d9-2b96-4995-93be-6ba65917dda3)

@Premkolte  assign me this

**Comment by kom-senapati** [comment]
But why we need login and signup page?

**Comment by Krishna100604** [comment]
> But why we need login and signup page?

if is it so why we need prices and all

**Comment by Krishna100604** [comment]
this is all designing the web later it can become more bigger project

**Comment by kom-senapati** [comment]
Also add the components into proper snippets
