### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by kom-senapati** [Premkolte/AnimateHub#12]
- Create a better README
- Create a Contributing.md
- Create issue templates(add a snippet, edit a snippet, bug fix of website, other) and pr template
- Bot to greet contributor who creates issue/PR.

This is not meant to be done by 1 person. Multiple people can do it.

**Comment by kom-senapati** [comment]
I will try to add readme tonight

**Comment by Premkolte** [comment]
Ok Sure

**Comment by Premkolte** [comment]
@kom-senapati comment in the #19 issue. (so that i want assign)

**Comment by deepesh611** [comment]
@Premkolte, do u need any other documentation updation ?

**Comment by Premkolte** [comment]
you can edit readme file, if you want to.. , and do add some snippets

**Comment by Premkolte** [comment]
@deepesh611 you can give a try to other open issues...

**Comment by deepesh611** [comment]
@Premkolte , I would like to work in the Greeting workflow, pls assign this issue to me

**Comment by Premkolte** [comment]
@deepesh611 raise a issue and ill assign you that
