### ISSUE TITLE
added tour to webiste in homepage

### ISSUE THREAD

**Issue by Krishna100604** [Premkolte/AnimateHub#120]
![Screenshot (213)](https://github.com/Premkolte/AnimateHub/assets/110299021/ac2993a0-b858-496b-950a-88cef0ca734c)
![Screenshot (212)](https://github.com/Premkolte/AnimateHub/assets/110299021/f18cc389-c4e7-44b1-8f0c-41a1b2664e98)
![Screenshot (211)](https://github.com/Premkolte/AnimateHub/assets/110299021/490a6f0f-8773-485a-a5d8-acfa6d107682)

@Premkolte  assign me this

**Comment by kom-senapati** [comment]
use react shepherd its better

**Comment by Krishna100604** [comment]
> use react shepherd its better

okk i will try

**Comment by Premkolte** [comment]
merged

**Comment by Premkolte** [comment]
its working fine upto 6/8 after that its not working

**Comment by Krishna100604** [comment]
> its working fine upto 6/8 after that its not working

thik hai dekhta hu me
