### ISSUE TITLE
PR run failed: Add Contributor

### ISSUE THREAD

**Issue by Premkolte** [Premkolte/AnimateHub#123]
**PR run failed: Add Contributor**

**Screenshots 📷**
<img width="1100" alt="Screenshot 2024-07-10 at 10 11 40 AM" src="https://github.com/Premkolte/AnimateHub/assets/100456448/028b272f-5ad6-4854-bac9-5180ec7c86de">

<img width="1440" alt="Screenshot 2024-07-10 at 11 37 29 AM" src="https://github.com/Premkolte/AnimateHub/assets/100456448/5de49238-5502-4b16-b93a-b81b4e9fe72a">

Please Solve this issue ASAP

**Comment by deepesh611** [comment]
Hi there @Premkolte , i can do this..

**Comment by deepesh611** [comment]
@Premkolte, I have submitted a PR, pls have a look

**Comment by deepesh611** [comment]
@Premkolte, if the workflow still gives issue, I can edit the contributors in the readme, such that it may not need the workflow

**Comment by Premkolte** [comment]
yes its giving this error
<img width="1056" alt="Screenshot 2024-07-16 at 12 30 29 PM" src="https://github.com/user-attachments/assets/75f4001d-9902-4ee7-afce-e73c90ac3d4d">

**Comment by Premkolte** [comment]
<img width="1078" alt="Screenshot 2024-07-16 at 12 31 58 PM" src="https://github.com/user-attachments/assets/e8e83dcb-5ea9-418f-9446-bf99c2d7bcd7">

**Comment by deepesh611** [comment]
hmm, could you give me the repo owner email id

**Comment by Premkolte** [comment]
premkolte26@gmail.com

**Comment by deepesh611** [comment]
@Premkolte, I have submitted another PR, pls have a look

**Comment by Premkolte** [comment]
<img width="1440" alt="Screenshot 2024-07-16 at 12 44 44 PM" src="https://github.com/user-attachments/assets/0b46e205-9f00-4dba-96ce-414ad30b152b">

**Comment by deepesh611** [comment]
could you pls open the error msg

**Comment by deepesh611** [comment]
> yes its giving this error <img alt="Screenshot 2024-07-16 at 12 30 29 PM" width="1056" src="https://private-user-images.githubusercontent.com/100456448/348975279-75f4001d-9902-4ee7-afce-e73c90ac3d4d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExMTQzMzEsIm5iZiI6MTcyMTExNDAzMSwicGF0aCI6Ii8xMDA0NTY0NDgvMzQ4OTc1Mjc5LTc1ZjQwMDFkLTk5MDItNGVlNy1hZmNlLWU3M2M5MGFjM2Q0ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxNlQwNzEzNTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MjMzOTRmYzk5ZGRjNjFlNmJiZWI5ODA4NTI5NzQxMWMwZDBjNmM1ZTFmNjkzYzc4MGZiOTNmZWIxMTZmMTMwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.GAG76dM3CjLbBCiLb8uq727pvvOfM-THHbGcIMvbDEU">

like this one

**Comment by Premkolte** [comment]
<img width="1440" alt="Screenshot 2024-07-16 at 12 46 49 PM" src="https://github.com/user-attachments/assets/c8773c3e-70b7-4ea8-901a-37d456f224a1">

**Comment by deepesh611** [comment]
did u try with a test PR ?

**Comment by Premkolte** [comment]
no

**Comment by Premkolte** [comment]
<img width="1437" alt="Screenshot 2024-07-16 at 12 49 35 PM" src="https://github.com/user-attachments/assets/139f3b59-5e4f-482e-bd24-242f33765948">

**Comment by deepesh611** [comment]
> no

create a test branch, and create a PR from test to main branch after doing some changes like adding a new blank line in readme or something, merge it in the main branch, then check

**Comment by Premkolte** [comment]
okk ill do that..

**Comment by deepesh611** [comment]
> <img alt="Screenshot 2024-07-16 at 12 49 35 PM" width="1437" src="https://private-user-images.githubusercontent.com/100456448/348980984-139f3b59-5e4f-482e-bd24-242f33765948.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExMTQ2ODUsIm5iZiI6MTcyMTExNDM4NSwicGF0aCI6Ii8xMDA0NTY0NDgvMzQ4OTgwOTg0LTEzOWYzYjU5LTVlNGYtNDgyZS1iZDI0LTI0MmYzMzc2NTk0OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxNlQwNzE5NDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMTBlYzk0MzY2ZmY4ZjQyNGZjMjU1YjBiN2RmM2U3MjExYWNlZTdjZTE0ZmMwZDQ4Y2YyYjE0YzBlN2I5ODc5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Fx28aMpEsL8P3ytzO9zAU5Bs4nm_EwiUNOJqZTEbFNM">

this script that ran was the one before the changes were updated, that is why it shows error, 
I have updated the script such that it is you who is accessing the repo and not the `github-actions[bot]`

**Comment by Premkolte** [comment]
<img width="1440" alt="Screenshot 2024-07-16 at 12 53 50 PM" src="https://github.com/user-attachments/assets/11a5c79b-acc4-4872-a7aa-331dbcd0e647">

**Comment by deepesh611** [comment]
and what's the msg this time ?

**Comment by deepesh611** [comment]
> I tried test PR, it still gives the same error

i see

 well, let's disable the workflow and update the readme contributor's section

**Comment by Premkolte** [comment]
<img width="1438" alt="Screenshot 2024-07-16 at 12 56 17 PM" src="https://github.com/user-attachments/assets/162df8ea-bc9d-4b70-a84f-c523303efbad">

**Comment by deepesh611** [comment]
@Premkolte, I have submitted a PR, pls have a look.

This might give u an error once, but u won't get it later on

**Comment by Premkolte** [comment]
no, it didn't give any error.

**Comment by deepesh611** [comment]
> no, it didn't give any error.

great

**Comment by deepesh611** [comment]
Pls make sure to update the points if I was of some help

email: deepeshvcd6273@gmail.com

**Comment by Premkolte** [comment]
yes sure.

**Comment by Premkolte** [comment]
now if new person contributes, his name will be added to contributors section automatically right??

**Comment by deepesh611** [comment]
> now if new person contributes, his name will be added to contributors section automatically on the website right??

do u mean the README ?

**Comment by Premkolte** [comment]
Solved.
