### ISSUE TITLE
[💡FEATURE] : Adding a favicon

### ISSUE THREAD

**Issue by Meetjain1** [Premkolte/AnimateHub#126]
**Is your feature request related to a problem? Please describe. 📝**
A clear and concise description of what the problem is.

**Describe the solution you'd like 🛠️**
Want to add a favicon to the website 

**Describe alternatives you've considered 🔄**

**Additional context 💬**

**Comment by Premkolte** [comment]
send me your email on discord.

**Comment by Meetjain1** [comment]
> send me your email on discord.

sure @Premkolte

**Comment by Meetjain1** [comment]
@Premkolte is there any logo already designed that should be place as a favicon,
or I have to design it let me know .

**Comment by Premkolte** [comment]
you can design one and comment in issue #6

**Comment by Meetjain1** [comment]
@Premkolte I have designed some logos have a look and let me know which suits best .

**Comment by Meetjain1** [comment]
> @Premkolte I have designed some logos have a look and let me know which suits best .

@Premkolte ?

**Comment by Premkolte** [comment]
@Meetjain1 I have mentioned it under logo issue
