### ISSUE TITLE
[💡FEATURE] Adding a tab group to the components

### ISSUE THREAD

**Issue by Mehak-Mattoo** [Premkolte/AnimateHub#156]
**Is your feature request related to a problem? Please describe. 📝**
Addition of tab group in components section 

**Describe the solution you'd like 🛠️**
Adding css amd js code for these kinds of tabs 

**Additional context 💬**

![Screenshot_2024-07-17-04-17-29-38_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/user-attachments/assets/c93dd242-7bb1-4c25-8a7e-7e34af2e5297)

**Comment by kom-senapati** [comment]
What tab group ? Isnt it already there
