### ISSUE TITLE
[💡FEATURE] Home button 

### ISSUE THREAD

**Issue by Mehak-Mattoo** [Premkolte/AnimateHub#158]
.
**Please describe.**
Addition of "go to home" button on the sidebar 

**Describe the solution you'd like**
As there is no navbar present throughout the website, a home button will help users to navigate on the website 

**Describe alternatives you've considered 🔄**

**Additional context 💬**

**Comment by kom-senapati** [comment]
Home button is not required here, logo takes us back to home and also our goal is to get user to dashboard not back to home as its just landing page

**Comment by Premkolte** [comment]
let her add, we'll see..does it look good or not..
