### ISSUE TITLE
add Radio Snippets

### ISSUE THREAD

**Issue by Premkolte** [Premkolte/AnimateHub#16]

**Comment by pandey22** [comment]
![image](https://github.com/Premkolte/AnimateHub/assets/35039432/d4c71829-cd13-40ca-8c0b-9cdb29427749)
I would like to contribute to this issue , the above snippet is a visual of how the Radio Snippet code would look like. Please assign me this issue.

**Comment by Premkolte** [comment]
Good job. Keep up the good work.
