### ISSUE TITLE
[🪲BUG] Add_contributor workflow failed

### ISSUE THREAD

**Issue by Premkolte** [Premkolte/AnimateHub#166]
**Describe the bug 📝**
workflow error

**Expected behavior ✅**
it should add contributors dynamically

**Screenshots 📷**
<img width="1440" alt="Screenshot 2024-07-17 at 11 38 59 AM" src="https://github.com/user-attachments/assets/a9a15eca-18ba-4686-bfd0-46e58385ce70">

**Comment by kom-senapati** [comment]
Assign me this issue
