### ISSUE TITLE
Update favicon

### ISSUE THREAD

**Issue by Premkolte** [Premkolte/AnimateHub#168]
**Describe the bug 📝**
favicon updation.

**Screenshots 📷**
change it to
<img width="311" alt="Screenshot 2024-07-17 at 11 43 29 AM" src="https://github.com/user-attachments/assets/ca06afd9-4269-4e25-a687-39a115681287">

**Comment by Meetjain1** [comment]
@Premkolte assign me

**Comment by Premkolte** [comment]
assigned
