### ISSUE TITLE
[💡FEATURE] Add FAQ section to `Contact Us` page

### ISSUE THREAD

**Issue by deepesh611** [Premkolte/AnimateHub#194]
**Is your feature request related to a problem? Please describe. 📝**
A clear and concise description of what the problem is.
Adding a FAQ section so that not everyone need to contact the developers/maintainers

**Describe the solution you'd like 🛠️**

**Describe alternatives you've considered 🔄**

**Additional context 💬**

**Comment by deepesh611** [comment]
btw, do you want the FAQ section to be above the Contact us form or below ?

**Comment by Premkolte** [comment]
below

**Comment by Premkolte** [comment]
or what you ever you say?

**Comment by deepesh611** [comment]
@Premkolte, I have added the FAQ section to the `Contact Us` page, pls have a look

**Comment by deepesh611** [comment]
@Premkolte pls don't forget to update the score on this as well as the last PR
