### ISSUE TITLE
Add a Separate Scrollbar to Sidebar.

### ISSUE THREAD

**Issue by Premkolte** [Premkolte/AnimateHub#29]
add a separate scrollbar to the sidebar where all the buttons are listed.

**Comment by Krishna100604** [comment]
> add a separate scrollbar to the sidebar where all the buttons are listed.

assign me this

**Comment by Krishna100604** [comment]
![image](https://github.com/Premkolte/AnimateHub/assets/110299021/d10fb2c3-73b3-4dfd-8dc0-790d6638878f)

i added it
