### ISSUE TITLE
Greetings Workflow

### ISSUE THREAD

**Issue by deepesh611** [Premkolte/AnimateHub#47]
Add Greetings to people raising their first issue or first PR on this repo

**Comment by deepesh611** [comment]
Would you like the greetings only on the user's first issue or first PR on youor repo, or on every issue and on every PR

**Comment by kom-senapati** [comment]
Add both it would be better

**Comment by deepesh611** [comment]
I have submitted a PR, pls have a look and leave a feedback @Premkolte

**Comment by Premkolte** [comment]
Great. Keep up the good work.
