### ISSUE TITLE
Add types of card snippets, Dropdown snippets,Inputfield snippets , implement copy to clipboard 

### ISSUE THREAD

**Issue by Sudhanva21** [Premkolte/AnimateHub#5]
Will add multiple card snippets and redirect page to when clicked on card snippets in sidebar

**Comment by Premkolte** [comment]
your issue is partially solved

**Comment by Sudhanva21** [comment]
@Premkolte  I have made the pull request , pls  merge it

**Comment by Premkolte** [comment]
Done. Merged it.
