### ISSUE TITLE
added progress bar

### ISSUE THREAD

**Issue by Krishna100604** [Premkolte/AnimateHub#57]
![image](https://github.com/Premkolte/AnimateHub/assets/110299021/20566d7c-e023-4d99-a955-f225ec7e41f1)

@Premkolte assign this

**Comment by Premkolte** [comment]
color of all the progress bar is same as green, isn't it should be different for each progress bar...

**Comment by Premkolte** [comment]
create a separate run button for each progress bar

**Comment by Krishna100604** [comment]
okk i will try tomm now i have another work

**Comment by Premkolte** [comment]
ok ok sure

**Comment by Krishna100604** [comment]
![image](https://github.com/Premkolte/AnimateHub/assets/110299021/b25003df-8768-409f-99eb-b1488c48bb6a)

@Premkolte issue resolved

**Comment by Premkolte** [comment]
Good. Keep up the good work .
