### ISSUE TITLE
Animate-Hub Logo

### ISSUE THREAD

**Issue by Premkolte** [Premkolte/AnimateHub#6]
Design a Logo for Animate-Hub and share your Figma link over here.

**Comment by Premkolte** [comment]
Try to make 3 to 4 different logos and put them here, then we will decide better one among them.

**Comment by Yaser-123** [comment]
It's me Yaser

**Comment by pandey22** [comment]
1)
 ![Animate-Hub logo](https://github.com/Premkolte/AnimateHub/assets/35039432/8799aa27-4f42-4e50-a3a2-a3360eacf2e5)
2) 
![image](https://github.com/Premkolte/AnimateHub/assets/35039432/3f7050e9-0c05-473c-8b8f-d40f11f049ed)
3) 
![image](https://github.com/Premkolte/AnimateHub/assets/35039432/84025b67-e198-449a-ac04-e4146ffc7843)

**Comment by pandey22** [comment]
![AnimateHubLogo](https://github.com/Premkolte/AnimateHub/assets/35039432/6233335e-4cda-4c20-b03b-7f18e5d7d150)
Another Logo Design idea , keeping in mind the color palette of your website

**Comment by Meetjain1** [comment]
@Premkolte have a look on these logos 

![ah4](https://github.com/user-attachments/assets/7a96d48f-ec4d-4c0e-8e55-7b63b7e3b675)
![ah3](https://github.com/user-attachments/assets/56cd6667-c20b-498b-9ebe-987b0afe0bee)
![ah2](https://github.com/user-attachments/assets/94434f24-dac3-490f-b4e4-492844d537a2)
![ah1](https://github.com/user-attachments/assets/b2d99a44-2bd1-4d85-b429-630bf3559428)
![ah5](https://github.com/user-attachments/assets/2ecf9f5b-762c-4c34-a0ac-81876a10335d)

**Comment by Premkolte** [comment]
2nd of @pandey22 suits best

**Comment by Premkolte** [comment]
@Meetjain1
