### ISSUE TITLE
changed styling of about us and contact page

### ISSUE THREAD

**Issue by Krishna100604** [Premkolte/AnimateHub#66]
![Screenshot (145)](https://github.com/Premkolte/AnimateHub/assets/110299021/ab0f6cf1-89ee-48b4-be2b-714ef8faa31a)

![Screenshot (146)](https://github.com/Premkolte/AnimateHub/assets/110299021/36568bd3-7c34-4a63-aa16-97410a9f8c4c)

@Premkolte assign it

**Comment by Premkolte** [comment]
Good Work
