### ISSUE TITLE
added chat bot UI

### ISSUE THREAD

**Issue by Krishna100604** [Premkolte/AnimateHub#73]
![image](https://github.com/Premkolte/AnimateHub/assets/110299021/57fd8d81-e8dc-4e69-a14e-935477c4b1e2)

@Premkolte assign me this

**Comment by kom-senapati** [comment]
What chatbot you gonna use, are you using some library or building from scratch ?

**Comment by Krishna100604** [comment]
> What chatbot you gonna use, are you using some library or building from scratch ?

i was trying with openAi Api but i didn;t work out

**Comment by kom-senapati** [comment]
Use Gemini API it has free API key which works

**Comment by Krishna100604** [comment]
> Use Gemini API it has free API key which works

okk

**Comment by Krishna100604** [comment]
> > Use Gemini API it has free API key which works
> 
okk but there is a problem while merging it

**Comment by Krishna100604** [comment]
it doesn't pass all the checks

**Comment by Premkolte** [comment]
anything i can do??

**Comment by kom-senapati** [comment]
I had changed the folder structure thats do one thing save that file somewhere and pull the changes then create that page

**Comment by Premkolte** [comment]
which file are you talking about??

**Comment by kom-senapati** [comment]
Oh sorry its in landing page
