### ISSUE TITLE
Improve the UI of features and testimonial section.

### ISSUE THREAD

**Issue by Premkolte** [Premkolte/AnimateHub#81]

**Comment by Mehak-Mattoo** [comment]
I can add random images of people at the testimonials and give both sections a separate background in both light and dark modes.

Can you assign me this issue @Premkolte

**Comment by Premkolte** [comment]
@Mehak-Mattoo are you registered under vsoc24?

**Comment by Mehak-Mattoo** [comment]
Yes, I am with email- mehakmattoo7@gmail.com
