### ISSUE TITLE
added chatbot UI and make contribution page work dynamically

### ISSUE THREAD

**Issue by Krishna100604** [Premkolte/AnimateHub#84]
![Screenshot (159)](https://github.com/Premkolte/AnimateHub/assets/110299021/bc73663d-8a8b-4604-b4d6-447c54b68d80)
![Screenshot (158)](https://github.com/Premkolte/AnimateHub/assets/110299021/f30f83b0-d690-42b4-8c44-2e53e1011647)

@Premkolte  assign me this

**Comment by kom-senapati** [comment]
Contributor page is dynamic only using local host so that we don't have to use github tokens

**Comment by Krishna100604** [comment]
> Contributor page is dynamic only using local host so that we don't have to use github tokens

np but i just added to fetch user every 60 seconds
