### ISSUE TITLE
Enhancing the dark theme

### ISSUE THREAD

**Issue by Mehak-Mattoo** [Premkolte/AnimateHub#96]
The dark theme on the website looks boring right now. I can add another bg color and another bg color for sections and cards.
 Can you assign this issue under VSOC 24. Thanks.

**Comment by Premkolte** [comment]
i think colors are fine for now... but you can give it a try.. then we will which one is looking good...

**Comment by Mehak-Mattoo** [comment]
Sure

**Comment by kom-senapati** [comment]
The dark theme is not proper its just using dark reader extension, proper dark theme need to be setup so yeah it have to be removed and a theme have to be added in total
